/** Auto-generated by scripts/wp-import.mjs — profile PDFs link to original site. */
export type TeamMember = {
	name: string;
	role: string;
	image: string;
	profilePdf: string | null;
};

export const teamMembers: TeamMember[] = [
	{
		"name": "Bobby Chandhoke",
		"role": "Senior Partner",
		"image": "Image-1-1-768x768.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Bobby-Chandhoke-Profile.pdf"
	},
	{
		"name": "Sudhir Sharma",
		"role": "Senior Partner",
		"image": "Sudhir-Sharma-Edited.png",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Sudhir-Sharma.pdf"
	},
	{
		"name": "Deepali Chandhoke",
		"role": "Senior Partner",
		"image": "image-3-1.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Deepali-Chandhoke-Profile.pdf"
	},
	{
		"name": "Amar Patnaik",
		"role": "Of-Counsel",
		"image": "cs-images-1080X1080-1.jpg.jpeg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Dr.-Amar-Patnaik-Profile.pdf"
	},
	{
		"name": "Saleem Hassan",
		"role": "Partner",
		"image": "image-4-1.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Saleem-Hasan-Ansari.pdf"
	},
	{
		"name": "Pradyuman Dubey",
		"role": "Partner",
		"image": "image-5.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Pradyuman-Dubey-Profile.pdf"
	},
	{
		"name": "Saurabh Tiwari",
		"role": "Partner",
		"image": "image-6.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Saurabh-Tiwari-Profile.pdf"
	},
	{
		"name": "Anant Garg",
		"role": "Partner",
		"image": "image-7.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Anant-Garg-Profile.pdf"
	},
	{
		"name": "Shalin Arthwan",
		"role": "Partner",
		"image": "image-8.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Shalin-Arthwan-Profile.pdf"
	},
	{
		"name": "Sharmistha Dube",
		"role": "Partner",
		"image": "image-9.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Sharmistha-Dube-Profile.pdf"
	},
	{
		"name": "Naman Singh Bagga",
		"role": "Partner",
		"image": "Naman-Singh-Bagga-Edited.png",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Naman-Singh-Bagga-Profile.pdf"
	},
	{
		"name": "Rugved More",
		"role": "Partner",
		"image": "Artboard-18d.jpg.jpeg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Rugved-More-Profile.pdf"
	},
	{
		"name": "Arbaaz Hussain",
		"role": "Managing Associate",
		"image": "image-11-1.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Arbaaz-Hussain-Profile.pdf"
	},
	{
		"name": "Surabhi Sahgal",
		"role": "Managing Associate",
		"image": "image-12.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Surabhi-Sahgal-Profile.pdf"
	},
	{
		"name": "Aimen Reshi",
		"role": "Managing Associate",
		"image": "image-14.jpg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Aimen-Reshi-Profile.pdf"
	},
	{
		"name": "Hriday Kochhar",
		"role": "Managing Associate",
		"image": "13.-Hriday-Kochhar-final-edited-1.png",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Hriday-Kochhar-profile-1.pdf"
	},
	{
		"name": "Anirudh Singh",
		"role": "Managing Associate",
		"image": "cs-images-1080X1080-3.jpg.jpeg",
		"profilePdf": "https://cspartners.in/wp-content/uploads/2026/03/Anirudh-Singh-Profile.pdf"
	},
	{
		"name": "Deepshikha Bhati",
		"role": "Senior Associate",
		"image": "Artboard-10.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Vasu Manchanda",
		"role": "Senior Associate",
		"image": "Artboard-11.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Neeharika Chauhan",
		"role": "Associate",
		"image": "cs-images-1080X1080.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Abhijeet Kumar",
		"role": "Associate",
		"image": "123.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Astha Dhawan",
		"role": "Associate",
		"image": "Artboard-14.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Deborshi Sarkar",
		"role": "Associate",
		"image": "1234.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Anshuman Arha",
		"role": "Associate",
		"image": "cs-images-1080X1080-2.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Kashish Mathur",
		"role": "Associate",
		"image": "cs-images-1080X1080-5.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Jayestha Kamboj",
		"role": "Associate",
		"image": "cs-images-1080X1080.jpg.jpeg",
		"profilePdf": null
	},
	{
		"name": "Arya Sharma",
		"role": "Associate",
		"image": "Artboard-15.jpg.jpeg",
		"profilePdf": null
	}
];
